name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  mac-ci:
    name: Mac app CI
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Xcode Debug build
        run: xcodebuild -project Cue3.xcodeproj -scheme Cue3 -configuration Debug build CODE_SIGNING_ALLOWED=NO

      - name: Xcode Release build
        run: xcodebuild -project Cue3.xcodeproj -scheme Cue3 -configuration Release build CODE_SIGNING_ALLOWED=NO
